/**
 * Database schema (SQLite).
 *
 * Two things drive the shape here beyond ordinary CRUD:
 *
 *  1. Assignments are append-only history. A week is never regenerated in
 *     place - once it exists it is the record of what people were told to do,
 *     which is the whole point of the app.
 *
 *  2. Every consequential action writes an `events` row. When somebody
 *     disputes a missed shift, the answer is a timestamped chain: posted on
 *     this date, flag window closed with no flag, marked absent afterwards.
 *
 * SQLite notes, for whoever reads this next:
 *  - Ids are text holding a UUID, generated in JS rather than by the database.
 *  - Dates are text in YYYY-MM-DD, which sorts and compares correctly.
 *  - Timestamps are integers (unix seconds); drizzle hands back Date objects.
 *  - Booleans are 0/1. Enums are text with the allowed set declared.
 */

import { randomUUID } from 'node:crypto';
import {
  sqliteTable,
  text,
  integer,
  real,
  index,
  uniqueIndex,
} from 'drizzle-orm/sqlite-core';

const CLASS_YEARS = ['sophomore', 'junior'] as const;
const MEALS = ['lunch', 'dinner'] as const;
const EXEMPT_REASONS = ['officer', 'medical', 'off-campus', 'other'] as const;
const WEEK_STATUSES = ['draft', 'posted', 'locked', 'complete'] as const;
const ASSIGNMENT_STATUSES = [
  'assigned',
  'flagged', // conflict raised; slot open to volunteers
  'covered', // someone else served; only they earn the point
  'no-show', // marked absent; generates make-up debt
  'excused', // waived by the manager, no debt
] as const;
const CONFLICT_SCOPES = ['semester', 'temporary'] as const;
const LATE_PLATE_STATUSES = [
  'waiting',   // requested; chef has not acted on it
  'ready',     // plated and on the shelf
  'declined',  // chef cannot make it; `reason` says why
  'cancelled', // brother cancelled himself
] as const;

const pk = () =>
  text('id')
    .primaryKey()
    .$defaultFn(() => randomUUID());

const created = () =>
  integer('created_at', { mode: 'timestamp' })
    .notNull()
    .$defaultFn(() => new Date());

/* ------------------------------------------------------------------ */

export const semesters = sqliteTable('semesters', {
  id: pk(),
  name: text('name').notNull(), // e.g. "Fall 2026"
  startsOn: text('starts_on').notNull(),
  endsOn: text('ends_on').notNull(),
  active: integer('active', { mode: 'boolean' }).notNull().default(false),

  /**
   * Kiosk token for the Chef Tablet. A random string generated by the admin,
   * passed in the URL to bypass sign-in for the late plates dashboard.
   */
  kioskToken: text('kiosk_token'),

  /**
   * Whether brothers are permitted to submit late plate requests.
   * Kitchen managers can turn this off to pause the tool during testing.
   */
  latePlatesEnabled: integer('late_plates_enabled', { mode: 'boolean' })
    .notNull()
    .default(true),

  /**
   * Optional custom logo URL to show on the Late Plate dashboard.
   */
  logoUrl: text('logo_url'),

  /**
   * Optional custom announcement message to display as a banner on the late plate dashboard.
   */
  latePlateMessage: text('late_plate_message'),

  /**
   * Which day/meal combinations late plates can be requested for, as
   * { lunch: boolean[7], dinner: boolean[7] } with index 0 = Monday.
   */
  latePlateDays: text('late_plate_days', { mode: 'json' }),

  /**
   * Which day/meal combinations the house serves, as
   * { lunch: boolean[7], dinner: boolean[7] } with index 0 = Monday.
   * Per-semester so it can change between Fall and Spring.
   */
  mealDays: text('meal_days', { mode: 'json' }).notNull(),
  /** { lunch: 2, dinner: 3 } - house rule, but stored rather than hardcoded. */
  slotSizes: text('slot_sizes', { mode: 'json' }).notNull(),

  createdAt: created(),
});

export const members = sqliteTable(
  'members',
  {
    id: pk(),
    name: text('name').notNull(),
    classYear: text('class_year', { enum: CLASS_YEARS }).notNull(),

    /**
     * Rotation priority. Lower is scheduled sooner. Increments by the
     * assignment multiplier, so a 3x pickup adds 3.
     *
     * Real rather than integer because half-point awards are allowed. Every
     * permitted multiplier is a multiple of 0.5, and halves are exact in
     * binary floating point, so these sums never drift.
     */
    points: real('points').notNull().default(0),

    /** Unworked make-up shifts owed from no-shows. Forces front of queue. */
    makeupDebt: integer('makeup_debt').notNull().default(0),

    exempt: integer('exempt', { mode: 'boolean' }).notNull().default(false),
    exemptReason: text('exempt_reason', { enum: EXEMPT_REASONS }),
    exemptNotes: text('exempt_notes'),

    /**
     * Scrypt hash of the member's 4-digit PIN. Null until they set one on
     * first sign-in. A PIN is weak by design - it exists to make actions
     * attributable, not to secure anything valuable.
     */
    pinHash: text('pin_hash'),

    /** Denormalized from assignments for fast tie-breaking during generation. */
    lastServedDate: text('last_served_date'),

    /**
     * Slack member id (e.g. U01ABC23DEF), so day-before reminders can @mention
     * the actual person rather than printing a name nobody is notified by.
     */
    slackUserId: text('slack_user_id'),

    /**
     * Standing allergens and dietary restrictions, as ids from
     * lib/dietary.ts. Remembered so a man with a peanut allergy does not have
     * to retick it every time he asks for a late plate - the tick he forgets
     * is the one that reaches a plate.
     *
     * Nullable rather than defaulted to '[]' so the migration can add it to a
     * roster that already exists; null and [] mean the same thing.
     */
    dietaryFlags: text('dietary_flags', { mode: 'json' }).$type<string[]>(),
    /** Free text for whatever the catalogue does not cover. */
    dietaryOther: text('dietary_other'),

    /** Off the roster (graduated, moved out) without deleting their history. */
    active: integer('active', { mode: 'boolean' }).notNull().default(true),

    createdAt: created(),
  },
  (t) => [
    index('members_year_idx').on(t.classYear),
    index('members_priority_idx').on(t.points, t.lastServedDate),
  ],
);

/**
 * Standing weekly conflicts - the primary defence against last-minute drama.
 * Because class year fixes the meal, one day index per row is sufficient.
 */
export const standingConflicts = sqliteTable(
  'standing_conflicts',
  {
    id: pk(),
    memberId: text('member_id')
      .notNull()
      .references(() => members.id, { onDelete: 'cascade' }),
    semesterId: text('semester_id')
      .notNull()
      .references(() => semesters.id, { onDelete: 'cascade' }),

    /** 0 = Monday ... 6 = Sunday. */
    dayIndex: integer('day_index').notNull(),
    note: text('note'), // "Chem lab"

    scope: text('scope', { enum: CONFLICT_SCOPES }).notNull().default('semester'),
    expiresOn: text('expires_on'),

    createdAt: created(),
  },
  (t) => [
    uniqueIndex('standing_conflict_unique').on(
      t.memberId,
      t.semesterId,
      t.dayIndex,
    ),
  ],
);

export const weeks = sqliteTable(
  'weeks',
  {
    id: pk(),
    semesterId: text('semester_id')
      .notNull()
      .references(() => semesters.id, { onDelete: 'cascade' }),

    /** ISO Monday this week starts. */
    weekStart: text('week_start').notNull(),
    status: text('status', { enum: WEEK_STATUSES }).notNull().default('posted'),

    /** Seed used to generate it, so the draw can be reproduced exactly. */
    seed: text('seed').notNull(),

    postedAt: integer('posted_at', { mode: 'timestamp' }),
    /** Server-anchored deadline. Never trust a phone clock for this. */
    locksAt: integer('locks_at', { mode: 'timestamp' }),
    lockedAt: integer('locked_at', { mode: 'timestamp' }),

    /**
     * True for the one-time first week of a semester, which cannot get the
     * normal full 7-day flag window because the semester starts the day after
     * the first chapter.
     */
    isBootstrap: integer('is_bootstrap', { mode: 'boolean' })
      .notNull()
      .default(false),

    createdAt: created(),
  },
  (t) => [uniqueIndex('weeks_semester_start_unique').on(t.semesterId, t.weekStart)],
);

export const slots = sqliteTable(
  'slots',
  {
    id: pk(),
    weekId: text('week_id')
      .notNull()
      .references(() => weeks.id, { onDelete: 'cascade' }),
    date: text('date').notNull(),
    meal: text('meal', { enum: MEALS }).notNull(),
    size: integer('size').notNull(),

    /**
     * What an unfilled seat on this shift is worth to whoever claims it.
     *
     * Lives on the slot rather than an assignment because an empty seat has no
     * assignment row to hang it from - and an empty seat is exactly when the
     * manager most needs to offer extra to get somebody to step up.
     */
    coverBounty: real('cover_bounty').notNull().default(1),
  },
  (t) => [
    uniqueIndex('slots_week_date_meal_unique').on(t.weekId, t.date, t.meal),
    index('slots_date_idx').on(t.date),
  ],
);

export const assignments = sqliteTable(
  'assignments',
  {
    id: pk(),
    slotId: text('slot_id')
      .notNull()
      .references(() => slots.id, { onDelete: 'cascade' }),
    memberId: text('member_id')
      .notNull()
      .references(() => members.id, { onDelete: 'restrict' }),

    status: text('status', { enum: ASSIGNMENT_STATUSES })
      .notNull()
      .default('assigned'),

    /** Who actually served, when someone covered. Only they earn the point. */
    coveredByMemberId: text('covered_by_member_id').references(() => members.id, {
      onDelete: 'set null',
    }),

    /**
     * Points this shift is worth to whoever serves it. 1 normally; the manager
     * can raise it to 1.5, 2, or 3 to get somebody to step up on short notice.
     */
    multiplier: real('multiplier').notNull().default(1),

    /** This assignment works off make-up debt - the one exception to 1/week. */
    isMakeup: integer('is_makeup', { mode: 'boolean' }).notNull().default(false),

    /**
     * Why the generator chose this person: points at pick time, days since
     * last served, eligible pool size. Frozen at generation so it stays true
     * even after the member's live numbers move on.
     */
    rationale: text('rationale', { mode: 'json' }),

    /** Set when points were actually credited, so we never double-credit. */
    settledAt: integer('settled_at', { mode: 'timestamp' }),

    /**
     * What settlement has already handed out for this shift. Kept so a later
     * attendance correction applies only the difference rather than
     * double-crediting or needing anyone to unwind points by hand.
     */
    pointsAwarded: real('points_awarded').notNull().default(0),
    debtAwarded: integer('debt_awarded').notNull().default(0),
    /** Who last received the points, so credit can be moved cleanly. */
    settledRecipientId: text('settled_recipient_id').references(() => members.id, {
      onDelete: 'set null',
    }),

    createdAt: created(),
  },
  (t) => [
    index('assignments_member_idx').on(t.memberId),
    index('assignments_slot_idx').on(t.slotId),
    uniqueIndex('assignments_slot_member_unique').on(t.slotId, t.memberId),
  ],
);

/**
 * Append-only audit log. This is the liability record - never update or delete
 * a row here. Written for: week posted, week locked, conflict flagged,
 * coverage claimed, attendance corrected, points adjusted, exemption changed,
 * roster edited.
 */
export const events = sqliteTable(
  'events',
  {
    id: pk(),
    action: text('action').notNull(),

    /** What the event is about, e.g. 'assignment' + the assignment id. */
    entityType: text('entity_type').notNull(),
    entityId: text('entity_id'),

    /** Who did it. Null for system actions. */
    actorMemberId: text('actor_member_id').references(() => members.id, {
      onDelete: 'set null',
    }),
    /** Denormalized so the log stays readable if a member is later removed. */
    actorName: text('actor_name'),

    /** Human-readable one-liner for the history view. */
    summary: text('summary').notNull(),
    payload: text('payload', { mode: 'json' }),

    createdAt: created(),
  },
  (t) => [
    index('events_entity_idx').on(t.entityType, t.entityId),
    index('events_actor_idx').on(t.actorMemberId),
    index('events_created_idx').on(t.createdAt),
  ],
);

/* ------------------------------------------------------------------ */
/* Late plates                                                         */
/* ------------------------------------------------------------------ */

/**
 * One row per brother per meal. A request is not deleted when it is cancelled
 * or declined - the row stays and its status changes, so the chefs can see
 * that somebody cancelled rather than wondering whether they missed a name.
 */
export const latePlates = sqliteTable(
  'late_plates',
  {
    id: pk(),
    memberId: text('member_id')
      .notNull()
      .references(() => members.id, { onDelete: 'cascade' }),

    /** ISO date of the meal, on the house's wall clock, not the requester's. */
    date: text('date').notNull(),
    meal: text('meal', { enum: MEALS }).notNull(),

    status: text('status', { enum: LATE_PLATE_STATUSES })
      .notNull()
      .default('waiting'),

    /** The brother's own note - "no onions", "grabbing it around 9". */
    note: text('note'),
    /** The chef's reason when declining. Their words, shown back to the brother. */
    reason: text('reason'),

    /**
     * The requester's allergens and restrictions as they stood when he asked.
     *
     * A snapshot, not a join to the member row. If he drops an allergy in
     * October, the plate the chefs made in September still says what they were
     * told at the time - which is the only version worth having in a record
     * anybody might later argue about.
     */
    flags: text('flags', { mode: 'json' }).$type<string[]>(),
    flagsOther: text('flags_other'),

    /**
     * Set when a chef confirmed they had read the flags. The server refuses to
     * mark a flagged plate ready without this, so the acknowledgement cannot be
     * skipped by a tablet that has not been updated - or by curl.
     */
    acknowledgedAt: integer('acknowledged_at', { mode: 'timestamp' }),
    acknowledgedBy: text('acknowledged_by'),

    requestedAt: integer('requested_at', { mode: 'timestamp' })
      .notNull()
      .$defaultFn(() => new Date()),
    /** When it stopped being 'waiting' - marked ready, declined, or cancelled. */
    resolvedAt: integer('resolved_at', { mode: 'timestamp' }),

    createdAt: created(),
  },
  (t) => [
    /**
     * One plate per man per meal. A cancelled request is reactivated in place
     * rather than inserted again, which is what keeps this constraint honest.
     */
    uniqueIndex('late_plates_member_meal_unique').on(t.memberId, t.date, t.meal),
    index('late_plates_date_idx').on(t.date, t.meal),
  ],
);

/**
 * Per-meal overrides of the house default cutoff.
 *
 * Rows exist only where a chef has changed something. An absent row means the
 * defaults in late-plate-service.ts apply, so the table stays empty in the
 * ordinary case instead of accumulating a row for every meal of the semester.
 */
export const latePlateSettings = sqliteTable(
  'late_plate_settings',
  {
    id: pk(),
    date: text('date').notNull(),
    meal: text('meal', { enum: MEALS }).notNull(),

    /** "HH:MM" on the house clock. Null means fall back to the house default. */
    cutoff: text('cutoff'),
    /** Chef has shut this meal to late plates entirely, cutoff or not. */
    closed: integer('closed', { mode: 'boolean' }).notNull().default(false),

    updatedAt: integer('updated_at', { mode: 'timestamp' })
      .notNull()
      .$defaultFn(() => new Date()),

    createdAt: created(),
  },
  (t) => [uniqueIndex('late_plate_settings_date_meal_unique').on(t.date, t.meal)],
);

/**
 * The cutoff each meal falls back to when nobody has set one for that day.
 *
 * This is what makes a chef's change stick. `late_plate_settings` holds one
 * day's decision; this holds the standing one, so a cutoff moved on Tuesday is
 * still in force on Wednesday without anybody setting it again.
 *
 * Deliberately holds only the cutoff. Closing a meal is a decision about
 * tonight - "kitchen closed for the night" - and carrying that forward would
 * silently refuse tomorrow's requests, which is the kind of failure nobody
 * would think to look for.
 */
export const latePlateMealDefaults = sqliteTable(
  'late_plate_meal_defaults',
  {
    id: pk(),
    meal: text('meal', { enum: MEALS }).notNull(),
    /** "HH:MM" on the house clock. */
    cutoff: text('cutoff').notNull(),

    updatedAt: integer('updated_at', { mode: 'timestamp' })
      .notNull()
      .$defaultFn(() => new Date()),
    /** Who last moved it, for the "since Tuesday" conversation. */
    updatedBy: text('updated_by'),

    createdAt: created(),
  },
  (t) => [uniqueIndex('late_plate_meal_defaults_meal_unique').on(t.meal)],
);

/**
 * Standing recurring weekly late plates scheduled by brothers.
 * (e.g. Every Tuesday Dinner, Every Thursday Lunch).
 */
export const recurringLatePlates = sqliteTable(
  'recurring_late_plates',
  {
    id: pk(),
    memberId: text('member_id')
      .notNull()
      .references(() => members.id, { onDelete: 'cascade' }),
    /** Day of week: 0 = Monday, 1 = Tuesday, 2 = Wednesday, 3 = Thursday, 4 = Friday, 5 = Saturday, 6 = Sunday */
    dayOfWeek: integer('day_of_week').notNull(),
    meal: text('meal', { enum: MEALS }).notNull(),
    note: text('note'),
    active: integer('active', { mode: 'boolean' }).notNull().default(true),
    createdAt: created(),
  },
  (t) => [
    uniqueIndex('recurring_late_plates_member_day_meal_unique').on(
      t.memberId,
      t.dayOfWeek,
      t.meal,
    ),
    index('recurring_late_plates_member_idx').on(t.memberId),
  ],
);

/**
 * TV Settings / Announcements Config.
 * Stored as a single row containing a JSON blob to match the flexibility
 * of the old `announcements.json` without requiring schema migrations
 * every time a new display setting is added.
 */
export const tvSettings = sqliteTable('tv_settings', {
  id: pk(),
  /** The full config object from the kitchen-tv app */
  config: text('config', { mode: 'json' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp' })
    .notNull()
    .$defaultFn(() => new Date()),
});


